### ISSUE TITLE
Installation script

### ISSUE THREAD

**Issue by jameswilson** [majksner/php-memcached-mamp#16]
I see that this repository is updated when MAMP comes out with a new version. 

How about a script that automates the installation/update process?

A script could check MAMP's `bin/` folder for versions of php and copy the corresponding memcached.so files into the right place. It could also search for and add the required lines to the php.ini files if they dont exist -- this could be done for php.ini files in both MAMP as well as MAMP Pro (which stores them in a separate place).

**Comment by majksner** [comment]
Pull requests are welcome, unfortunately at this moment I don't have time to write that script.

**Comment by vbauer** [comment]
:+1:
