### ISSUE TITLE
MAMP 3.2.1 with PHP 5.6.7

### ISSUE THREAD

**Issue by GregoryClaeyssens** [majksner/php-memcached-mamp#18]
Hi I tried your instructions but I get following error in my log
/Applications/MAMP/bin/php/php5.6.7/lib/php/extensions/no-debug-non-zts-20131226/memcached.so: unknown file type, first eight bytes: 0x0A 0x0A 0x0A 0x3C 0x21 0x44 0x4F 0x43 in Unknown on line 0

I presume it's because I tried your php 5.6.2 memcached.so while I would need a 5.6.7 version.

I tried doing it manually (with make etc) but I soon got stuck way over my head, needing to add components like php_session.h etc...

How can I make this work for MAMP 3.2.1 with PHP 5.6.7?

Thank you in advance

**Comment by shql** [comment]
Hey, since I stepped over the same issue I am following this guide to make it work in a much nicer way to be honest. Looks like a lot to do but you can have it run in like 5 minutes. Hope this helps.

https://www.silviogutierrez.com/blog/drupal-6-and-memcached-mamp/

**Comment by GregoryClaeyssens** [comment]
Thanks, was sceptical since this was for php 5.2... but it's still relevant. Worked like a charm
