### ISSUE TITLE
Unable to Load Dynamic Library 

### ISSUE THREAD

**Issue by justincolangelo** [majksner/php-memcached-mamp#22]
Here is the message I receive after downloading the `memcached.so` file and placing it in the appropriate folder, then adding the module reference to `php.ini` (MAMP 3.5 is that the issue?):

> PHP Startup: Unable to load dynamic library '/Applications/MAMP/bin/php/php5.6.10/lib/php/extensions/no-debug-non-zts-20131226/memcached.so' - dlopen(/Applications/MAMP/bin/php/php5.6.10/lib/php/extensions/no-debug-non-zts-20131226/memcached.so, 9): no suitable image found.  Did find:
	/Applications/MAMP/bin/php/php5.6.10/lib/php/extensions/no-debug-non-zts-20131226/memcached.so: unknown file type, first eight bytes: 0x0A 0x0A 0x0A 0x0A 0x3C 0x21 0x44 0x4F in Unknown on line 0

Do you know what may be happening?

**Comment by majksner** [comment]
Make sure you have file on appropriate location and correct permissions on it.
