### ISSUE TITLE
Mamp 3.5.2 / php 7.0.8 not working

### ISSUE THREAD

**Issue by TheoPipaud** [majksner/php-memcached-mamp#24]
works great with my previous version of MAMP 2 (php 5.6.x) 
but not with current release of MAMP 3. 

i put the `extension=memcached.so` after all extensions (instead of end of `php.ini`)
like this : 

```
; Extensions

;extension=apcu.so
;extension=apc.so

extension=imap.so
;extension=yaz.so
extension=mcrypt.so
extension=gettext.so
extension=pgsql.so
extension=pdo_pgsql.so

;extension=imagick.so
;extension=tidy.so
;extension=oauth.so

extension=memcached.so
```

Apache starts, but php return an error `Fatal error: Uncaught Error: Class 'Memcached' not found
`

**Comment by majksner** [comment]
Just updated repo. Check for new .so file
